version: "3"

volumes:
    mysql_vol:
  
services: 
    app:
        container_name: app
        environment:
            - "GOPATH=/go"
        build: 
            context: ./app
            dockerfile: Dockerfile
            args:
                - GoogleClientID=test
                - GoogleClientSecret=test
        tty: true
        volumes:
            - ./app:/go/src/Junking
        ports: 
            - "80:8080"
        depends_on: 
            - db

    db:
        container_name: db
        build:
            context: ./db
            dockerfile: Dockerfile
        volumes:
        - mysql_vol:/var/lib/mysql:delegated
        environment:
        - MYSQL_ROOT_PASSWORD=test
        ports:
        - "3306:3306"        
