# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - junking

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://junking.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_fc138dccd6b747929922b5de55748f7d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a185556934004f7da63a287cd7cde379 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: junking.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_fc138dccd6b747929922b5de55748f7d }}/junking-image:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'junking'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_18f1aa34b4114a61b309ff9d9e8b6111 }}
        images: 'junking.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_fc138dccd6b747929922b5de55748f7d }}/junking-image:${{ github.sha }}'